// scripts/sync-content.mjs
// 构建期快照：从内容仓库（公开）拉取「已发布」攻略，生成 src/data/generated.ts。
// 数据源：
//   - 默认：GitHub raw（公开仓库，免鉴权）
//       OWNER/REPO/BRANCH 可经环境变量覆盖（见下）
//   - 本地模式：设置 CONTENT_LOCAL_DIR 指向本地内容仓库目录（用于离线/开发）
// 失败时写入空兜底，保证仓库始终可编译（站点回退到 src/data/*.ts 静态攻略）。
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const PROJECT = process.cwd();
const OUT_FILE = path.join(PROJECT, "src", "data", "generated.ts");

const OWNER = process.env.CONTENT_OWNER || "heyxiaoze";
const REPO = process.env.CONTENT_REPO || "travel-guide-content";
const BRANCH = process.env.CONTENT_BRANCH || "main";
const LOCAL_DIR = process.env.CONTENT_LOCAL_DIR
  ? path.resolve(PROJECT, process.env.CONTENT_LOCAL_DIR)
  : null;

const FALLBACK = `// AUTO-GENERATED fallback (sync failed). Do not edit.
import type { Guide } from "@/types/guide";

export const CONTENT_GUIDES: Record<string, Guide> = {};
export const CONTENT_ORDER: string[] = [];
`;

async function readJsonLocal(p) {
  const raw = await readFile(p, "utf8");
  return JSON.parse(raw);
}

async function readJsonRemote(url) {
  const res = await fetch(url, { redirect: "follow" });
  if (!res.ok) throw new Error(`GET ${url} -> ${res.status}`);
  return res.json();
}

async function readJson(rel) {
  if (LOCAL_DIR) return readJsonLocal(path.join(LOCAL_DIR, "guides", rel));
  return readJsonRemote(
    `https://raw.githubusercontent.com/${OWNER}/${REPO}/${BRANCH}/guides/${rel}`,
  );
}

async function main() {
  let index;
  try {
    index = await readJson("index.json");
  } catch (e) {
    console.warn(`[sync-content] 无法读取 index.json（${e.message}）→ 写空兜底，回退静态攻略。`);
    await writeFile(OUT_FILE, FALLBACK, "utf8");
    return;
  }

  const published = index.filter((g) => g.status === "published");
  const guides = {};
  const order = [];
  for (const meta of published) {
    try {
      const guide = await readJson(`${meta.id}.json`);
      guides[meta.id] = guide;
      order.push(meta.id);
    } catch (e) {
      console.warn(`[sync-content] 跳过 ${meta.id}（${e.message}）`);
    }
  }

  const ts = `// AUTO-GENERATED by scripts/sync-content.mjs — do not edit.
// 数据源：${LOCAL_DIR ? "本地目录 " + LOCAL_DIR : `GitHub ${OWNER}/${REPO}@${BRANCH}`}
// 仅包含已发布(status:"published")攻略；草稿不进入游客快照。
import type { Guide } from "@/types/guide";

export const CONTENT_GUIDES: Record<string, Guide> = (${JSON.stringify(
    guides,
    null,
    2,
  )}) as Record<string, Guide>;

export const CONTENT_ORDER: string[] = ${JSON.stringify(order, null, 2)};
`;

  await writeFile(OUT_FILE, ts, "utf8");
  console.log(
    `[sync-content] 已生成 ${OUT_FILE}：收录 ${order.length} 篇已发布攻略（共 ${index.length} 篇）。`,
  );
}

main().catch((e) => {
  console.error("[sync-content] 异常，写空兜底：", e);
  writeFile(OUT_FILE, FALLBACK, "utf8").catch(() => {});
  process.exit(0); // 不让构建因内容源临时不可达而失败
});
